import 'package:restorant/models/foods_Model.dart';

List<TopModel> foodsInfo = [
  TopModel(name: 'pizza', selected: false),
  TopModel(name: 'cake', selected: false),
  TopModel(name: 'salad', selected: false),
  TopModel(name: 'drink', selected: false),
];
List<FoodModel> pizza = [
  FoodModel(
      about: 'It makes with some cheese,tomatos and meat',
      cost: 69000,
      image: 'assets/c2.jpg',
      name: 'Spicy',
      category: 'Pizza',
      count: 1,
      bool1: false,
      bool2: false,
      bool3: false,
      bool4: false,
      bool5: false,
      ctg1: 'meet',
      ctg2: 'cheese',
      ctg3: 'little',
      ctg4: 'medium',
      ctg5: 'big'),
  FoodModel(
      cost: 69000,
      image: 'assets/c2.jpg',
      name: 'Spicy',
      category: 'Pizza',
      count: 1),
  FoodModel(
      cost: 69000,
      image: 'assets/c2.jpg',
      name: 'Spicy',
      category: 'Pizza',
      count: 1),
  FoodModel(
      cost: 69000,
      image: 'assets/c2.jpg',
      name: 'Spicy',
      category: 'Pizza',
      count: 1),
  FoodModel(
      cost: 69000,
      image: 'assets/c2.jpg',
      name: 'Spicy',
      category: 'Pizza',
      count: 1),
  FoodModel(
      cost: 69000,
      image: 'assets/c2.jpg',
      name: 'Spicy',
      category: 'Pizza',
      count: 1),
  FoodModel(
      cost: 69000,
      image: 'assets/c2.jpg',
      name: 'Spicy',
      category: 'Pizza',
      count: 0),
  FoodModel(
      cost: 69000,
      image: 'assets/c2.jpg',
      name: 'Spicy',
      category: 'Pizza',
      count: 0),
  FoodModel(
      cost: 69000,
      image: 'assets/c2.jpg',
      name: 'Cherry',
      category: 'Cake',
      count: 0),
  FoodModel(
      cost: 69000,
      image: 'assets/c2.jpg',
      name: 'Cherry',
      category: 'Cake',
      count: 0),
  FoodModel(
      cost: 69000,
      image: 'assets/c2.jpg',
      name: 'Cherry',
      category: 'Cake',
      count: 0),
  FoodModel(
      cost: 69000,
      image: 'assets/c2.jpg',
      name: 'Cherry',
      category: 'Cake',
      count: 0),
  FoodModel(
      cost: 69000,
      image: 'assets/c2.jpg',
      name: 'Cherry',
      category: 'Cake',
      count: 0),
  FoodModel(
      cost: 69000,
      image: 'assets/c2.jpg',
      name: 'Cherry',
      category: 'Cake',
      count: 0),
  FoodModel(
      cost: 69000,
      image: 'assets/c2.jpg',
      name: 'Cherry',
      category: 'Cake',
      count: 0),
  FoodModel(
      cost: 69000,
      image: 'assets/c2.jpg',
      name: 'Cherry',
      category: 'Cake',
      count: 0),
  FoodModel(
      cost: 69000,
      image: 'assets/c2.jpg',
      name: 'Sezar',
      category: 'Salad',
      count: 0),
  FoodModel(
      cost: 69000,
      image: 'assets/c2.jpg',
      name: 'Sezar',
      category: 'Salad',
      count: 0),
  FoodModel(
      cost: 69000,
      image: 'assets/c2.jpg',
      name: 'Sezar',
      category: 'Salad',
      count: 0),
  FoodModel(
      cost: 69000,
      image: 'assets/c2.jpg',
      name: 'Sezar',
      category: 'Salad',
      count: 0),
  FoodModel(
      cost: 69000,
      image: 'assets/c2.jpg',
      name: 'Sezar',
      category: 'Salad',
      count: 0),
  FoodModel(
      cost: 69000,
      image: 'assets/c2.jpg',
      name: 'Sezar',
      category: 'Salad',
      count: 0),
  FoodModel(
      cost: 69000,
      image: 'assets/c2.jpg',
      name: 'Sezar',
      category: 'Salad',
      count: 0),
  FoodModel(
      cost: 69000,
      image: 'assets/c2.jpg',
      name: 'Sezar',
      category: 'Salad',
      count: 0),
  FoodModel(
      cost: 69000,
      image: 'assets/c2.jpg',
      name: 'Pepsi',
      category: 'Drink',
      count: 0),
  FoodModel(
      cost: 69000,
      image: 'assets/c2.jpg',
      name: 'Pepsi',
      category: 'Drink',
      count: 0),
  FoodModel(
      cost: 69000,
      image: 'assets/c2.jpg',
      name: 'Pepsi',
      category: 'Drink',
      count: 0),
  FoodModel(
      cost: 69000,
      image: 'assets/c2.jpg',
      name: 'Pepsi',
      category: 'Drink',
      count: 0),
  FoodModel(
      cost: 69000,
      image: 'assets/c2.jpg',
      name: 'Pepsi',
      category: 'Drink',
      count: 0),
  FoodModel(
      cost: 69000,
      image: 'assets/c2.jpg',
      name: 'Pepsi',
      category: 'Drink',
      count: 0),
  FoodModel(
      cost: 69000,
      image: 'assets/c2.jpg',
      name: 'Pepsi',
      category: 'Drink',
      count: 0),
  FoodModel(
      cost: 69000,
      image: 'assets/c2.jpg',
      name: 'Pepsi',
      category: 'Drink',
      count: 0),
];
List<FoodModel> additional = [
  FoodModel(
      cost: 69000,
      image: 'assets/c2.jpg',
      name: 'Cherry',
      category: 'Cake',
      count: 0),
  FoodModel(
      cost: 69000,
      image: 'assets/c2.jpg',
      name: 'Pepsi',
      category: 'Drink',
      count: 0),
  FoodModel(
      cost: 69000,
      image: 'assets/c2.jpg',
      name: 'Pepsi',
      category: 'Drink',
      count: 0),
  FoodModel(
      cost: 69000,
      image: 'assets/c2.jpg',
      name: 'Pepsi',
      category: 'Drink',
      count: 0),
  FoodModel(
      cost: 69000,
      image: 'assets/c2.jpg',
      name: 'Pepsi',
      category: 'Drink',
      count: 0),
];
